[BD-35] PAR-284 feat: change popover component according to new design
edx/paragon pull request #662
Opened 2021-03-17 21:10 UTC by amalbas

@abutterworth 
Ticket in Jira: https://openedx.atlassian.net/browse/PAR-284
Update popover component according to new design, add success, warning and danger variants
![popover-old](https://user-images.githubusercontent.com/36944773/111538887-3cee4300-873b-11eb-9fa8-3192cff49920.jpg)
![popover-new](https://user-images.githubusercontent.com/36944773/111538892-3e1f7000-873b-11eb-8f97-2f704dcb55d1.jpg)

2021-03-17 21:10 UTC, edx-webhook commented
Thanks for the pull request, @amalbas! I've created [BLENDED-798](https://openedx.atlassian.net/browse/BLENDED-798) to keep track of it in Jira.


When this pull request is ready, tag your edX technical lead.


<!-- comment:welcome-blended -->
<!-- jenkins ok to test -->
<!-- data: eyJkcmFmdCI6IGZhbHNlfQ== -->

2021-03-22 12:36 UTC, abutterworth commented on src/Popover/Popover.scss
> +        margin-right: $popover-icon-margin-right;
The icon in the design is forced to be 16px by 16x.

```suggestion
        margin-right: $popover-icon-margin-right;
        height: 1rem;
        width: 1rem;
```

2021-03-22 12:38 UTC, abutterworth requested changes
See comments

2021-04-06 14:15 UTC, abutterworth approved these changes

2021-04-06 14:15 UTC, merged

2021-04-06 14:21 UTC, edx-semantic-release commented
:tada: This PR is included in version 14.1.1 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@edx/paragon/v/14.1.1)
- [GitHub release](https://github.com/edx/paragon/releases/tag/v14.1.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: