[BD-35] PAR-291 feat: change alert component according to new design
edx/paragon pull request #663
Opened 2021-03-19 00:57 UTC by amalbas

@abutterworth 
Ticket in Jira: https://openedx.atlassian.net/browse/PAR-291
Change alert component according to new design
![alert-old](https://user-images.githubusercontent.com/36944773/111716483-2839aa00-8824-11eb-9292-af52e22f1c71.jpg)
![alert-new](https://user-images.githubusercontent.com/36944773/111716490-296ad700-8824-11eb-8594-90d9e6f7f5ef.jpg)

2021-03-19 00:57 UTC, edx-webhook commented
Thanks for the pull request, @amalbas! I've created [BLENDED-800](https://openedx.atlassian.net/browse/BLENDED-800) to keep track of it in Jira.


When this pull request is ready, tag your edX technical lead.


<!-- comment:welcome-blended -->
<!-- jenkins ok to test -->
<!-- data: eyJkcmFmdCI6IGZhbHNlfQ== -->

2021-03-22 12:40 UTC, abutterworth commented on src/Alert/Alert.scss
> -  border: $alert-border-width solid transparent;
Rather than deleting this: let's set `$alert-border-width` to `0` in Alert/_variables.scss

2021-03-22 12:51 UTC, abutterworth requested changes
Could we add a rule to ensure the last child of an alert has no margin? Without it we'll end up with extra space on the bottom edge

![image](https://user-images.githubusercontent.com/1615421/111992362-b1cecd80-8aeb-11eb-9556-ae61a0458d50.png)

2021-03-30 15:04 UTC, abutterworth approved these changes

2021-03-30 15:04 UTC, merged

2021-03-30 15:10 UTC, edx-semantic-release commented
:tada: This PR is included in version 13.17.5 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@edx/paragon/v/13.17.5)
- [GitHub release](https://github.com/edx/paragon/releases/tag/v13.17.5)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: