fix: remove opacity on stateful button
edx/paragon pull request #774
Opened 2021-07-01 23:17 UTC by uzairr

Remove the opacity on pending state of the stateful button so that a crisp original color would be displayed in pending state.

VAN-605

2021-07-05 13:29 UTC, awaisdar001 commented
@uzairr can you add before/after screenshots?

2021-07-05 13:45 UTC, raq929 commented
We still need there to be an opacity change when a button is actually disabled instead of pending.
Is there another option for your pending state?
Off the top of my head, you could put a spinner icon on the button, or have the button not show up until it's available to be used.
I think it will be a breaking change for other button users if this is merged; I certainly depend on that opacity change when the button is disabled.

2021-07-06 12:55 UTC, abutterworth requested changes
Please address @raq929 's point. We should not remove the style as in this PR. We could instead add opacity: 1 to a new selector put in https://github.com/edx/paragon/blob/master/src/StatefulButton/StatefulButton.scss 

See where class names are generated in Stateful Button:
https://github.com/edx/paragon/blob/master/src/StatefulButton/index.jsx#L78

2021-07-06 23:40 UTC, uzairr commented
I updated the PR as per the suggestions.Thanks everyone,
@raq929 please review the changes again.

2021-07-07 13:01 UTC, abutterworth approved these changes

2021-07-07 21:32 UTC, merged

2021-07-07 21:37 UTC, edx-semantic-release commented
:tada: This PR is included in version 16.0.2 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@edx/paragon/v/16.0.2)
- [GitHub release](https://github.com/edx/paragon/releases/tag/v16.0.2)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: